### ISSUE TITLE
MAVError is an undefined name in generator/mavparse.py

### ISSUE THREAD

**Issue by cclauss** [ArduPilot/pymavlink#116]
`MAVError` is [defined in `generator/mavgen_python.py`](https://github.com/ArduPilot/pymavlink/blob/master/generator/mavgen_python.py#L377) and is [used in `generator/mavparse.py`](https://github.com/ArduPilot/pymavlink/blob/master/generator/mavparse.py#L107) but is never imported.

**Comment by amilcarlucas** [comment]
No file changes here. why ?

**Comment by cclauss** [comment]
@amilcarlucas My attempt to fix resulted in circular imports so I opened an issue in hopes that fresh eyes could find a solution.
