### ISSUE TITLE
Python interface for custom dialect

### ISSUE THREAD

**Issue by JesperChristensen89** [ArduPilot/pymavlink#124]
I am able to generate the needed files for MAVLink in C with only a few custom messages (no common etc.). 
However, for Python I can't get the same routine to work. I can generate the .py file with my messages, but I still want to utilize some functions from mavutils. How do I achieve this? 
I.e. opening a serial interface and only utilizing say 2 custom messages.

**Comment by OXINARF** [comment]
I don't see any issue for doing that. What exact problem are you having?

**Comment by amilcarlucas** [comment]
No answer for almost a year now. Closing
