### ISSUE TITLE
MAV_CMD_DO_SET_SERVO using pymavlink

### ISSUE THREAD

**Issue by dinesh286** [ArduPilot/pymavlink#156]
I have to use MAV_CMD_DO_SET_SERVO mavlink command in pymavlink for controlling a fixed wing UAV. Is there any syntax available. I tried channeloverride in dronekit python and its working. since i want to put my own control algorithm in a companion computer and many advised not to use channeloverride i want to use MAV_CMD_DO_SET_SERVO.

**Comment by amilcarlucas** [comment]
That is currently already possible. This is not a bug, nor a missing feature.

**Comment by auturgy** [comment]
Agree with amilcar - perhaps visit the pymavlink gitter channel:
gitter.im/ArduPilot/pymavlink
