### ISSUE TITLE
self._endian = pcap.None  # invalid syntax in Python3

### ISSUE THREAD

**Issue by cclauss** [ArduPilot/pymavlink#18]
https://github.com/ArduPilot/pymavlink/blob/master/examples/mav2pcap.py#L62

I am unsure how to fix this.

**Comment by peterbarker** [comment]
On Tue, 11 Oct 2016, cclauss wrote:

> https://github.com/ArduPilot/pymavlink/blob/master/examples/mav2pcap.py#L62
> I am unsure how to fix this.

Maybe remove the example?

I was certainly tempted earlier today :-)

**Comment by khancyr** [comment]
I vote for removal too ! I don't remember which, but some other examples aren't working...
