### ISSUE TITLE
DFReader broken for PX4

### ISSUE THREAD

**Issue by devbharat** [ArduPilot/pymavlink#2]
Uses function `mode_string_px4` [here](https://github.com/ArduPilot/pymavlink/blob/master/DFReader.py#L470) which is no longer there.

**Comment by peterbarker** [comment]
Please provide a failing log.

**Comment by devbharat** [comment]
I use MAVExplorer which uses DFReader which calls the function `mode_string_px4(mode_number)` which was removed in [this commit](https://github.com/ArduPilot/pymavlink/commit/e67f707c4c56b010c962300516c83f6df3e54a8c), but not replaced in the DFReader.py file. 

Pretty much any PX4 log will fail when read with DFReader( as done by MAVExplorer). For example, this
http://logs.uaventure.com/view/rV9PLoSWvQHhd2JzTuuoFJ.

**Comment by peterbarker** [comment]
I've pushed in a fix for this.  The log you supplied now seems to parse and graph OK.

Closing for now.  Thanks for the bug report, and reopen this if I've messed up!
