### ISSUE TITLE
Melodic mavlink ROS package missing pymavlink

### ISSUE THREAD

**Issue by cberner** [ArduPilot/pymavlink#209]
The latest ROS packages for melodic don't seem to include pymavlink, even though the wiki states that they do: http://wiki.ros.org/mavlink

Originally reported in `mavlink/mavlink` (https://github.com/mavlink/mavlink/issues/931), but was told to report it here instead.

**Comment by khancyr** [comment]
Hello,
It is just the documentation that is wrong. Just pip install pymavlink

**Comment by cberner** [comment]
I see. The `python-pymavlink` rosdep can't be used by packages that are distributed as .debs, but I'll look for a work around
