### ISSUE TITLE
Erle robotics , Configuring Ubuntu machine

### ISSUE THREAD

**Issue by Braggg** [ArduPilot/pymavlink#221]
Hey guys, can someone help me, please?

bragg@bragg:~$ sudo pip2 install pymavlink catkin_pkg --upgrade
Downloading/unpacking pymavlink
  Downloading pymavlink-2.2.11.tar.gz (3.0MB): 3.0MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pymavlink/setup.py) egg_info for package pymavlink
    
Downloading/unpacking catkin-pkg
  Downloading catkin_pkg-0.4.8.tar.gz (58kB): 58kB downloaded
  Running setup.py (path:/tmp/pip_build_root/catkin-pkg/setup.py) egg_info for package catkin-pkg
    
Requirement already up-to-date: future in /usr/local/lib/python2.7/dist-packages (from pymavlink)
Downloading/unpacking lxml from https://files.pythonhosted.org/packages/4b/20/ddf5eb3bd5c57582d2b4652b4bbcf8da301bdfe5d805cb94e805f4d7464d/lxml-4.2.5.tar.gz#sha256=36720698c29e7a9626a0dc802ef8885f8f0239bfd1689628ecd459a061f2807f (from pymavlink)
  Downloading lxml-4.2.5.tar.gz (4.4MB): 4.4MB downloaded
  Running setup.py (path:/tmp/pip_build_root/lxml/setup.py) egg_info for package lxml
    Building lxml version 4.2.5.
    Building without Cython.
    Using build configuration of libxslt 1.1.28
    
    warning: no previously-included files found matching '*.py'
Downloading/unpacking argparse from https://files.pythonhosted.org/packages/f2/94/3af39d34be01a24a6e65433d19e107099374224905f1e0cc6bbe1fd22a2f/argparse-1.4.0-py2.py3-none-any.whl#sha256=c31647edb69fd3d465a847ea3157d37bed1f95f19760b11a47aa91c04b666314 (from catkin-pkg)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
Downloading/unpacking docutils (from catkin-pkg)
  Downloading docutils-0.14-py2-none-any.whl (543kB): 543kB downloaded
Downloading/unpacking python-dateutil from https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl#sha256=1adb80e7a782c12e52ef9a8182bebeb73f1d7e24e374397af06fb4956c8dc5c0 (from catkin-pkg)
  Downloading python_dateutil-2.7.3-py2.py3-none-any.whl (211kB): 211kB downloaded
Downloading/unpacking pyparsing from https://files.pythonhosted.org/packages/42/47/e6d51aef3d0393f7d343592d63a73beee2a8d3d69c22b053e252c6cfacd5/pyparsing-2.2.1-py2.py3-none-any.whl#sha256=905d8090c335314568b5faee0025b1829f27bb974604a5762a6cdef3a7dfc3b7 (from catkin-pkg)
  Downloading pyparsing-2.2.1-py2.py3-none-any.whl (57kB): 57kB downloaded
Downloading/unpacking six>=1.5 from https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl#sha256=832dc0e10feb1aa2c68dcc57dbb658f1c7e65b9b61af69048abc87a2db00a0eb (from python-dateutil->catkin-pkg)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: pymavlink, catkin-pkg, lxml, argparse, docutils, python-dateutil, pyparsing, six
  Running setup.py install for pymavlink
    No XML message definitions found
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pymavlink/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JJxvOY-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

No XML message definitions found

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pymavlink/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-JJxvOY-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/pymavlink
Storing debug log for failure in /home/bragg/.pip/pip.log

**Comment by khancyr** [comment]
This was an error in the release. Please update with the new version.
