### ISSUE TITLE
C mavlink_parse_char: r_mavlink_status misleading

### ISSUE THREAD

**Issue by michprev** [ArduPilot/pymavlink#277]
Redirected from https://github.com/mavlink/mavlink/issues/1086
Also see https://github.com/ArduPilot/pymavlink/issues/95#issuecomment-318449846

Talking about the last argument of
https://github.com/ArduPilot/pymavlink/blob/fc57c0943a9a6b03d18ef801d256b95d43cd3ff6/generator/C/include_v2.0/mavlink_helpers.h#L953

The only place where status is assigned to is
https://github.com/ArduPilot/pymavlink/blob/fc57c0943a9a6b03d18ef801d256b95d43cd3ff6/generator/C/include_v2.0/mavlink_helpers.h#L807-L814

That implies following:
- some attributes are never assigned
- I don't see a difference between `packet_rx_drop_count` and `parse_error`

If it does not make sense to provide some information to the caller of `mavlink_parse_char` it would be better to make a new struct where all attributes will be assigned to.

**Comment by magicrub** [comment]
Not all variables make sense to use all the time. For example, that struct is used twice in the declaration of [mavlink_frame_char_buffer()](https://github.com/ArduPilot/pymavlink/blob/fc57c0943a9a6b03d18ef801d256b95d43cd3ff6/generator/C/include_v2.0/mavlink_helpers.h#L547).

Also, those structs can be edited externally by the application layer.  For example, [here's ArduPilot doing it](https://github.com/ArduPilot/ardupilot/blob/master/libraries/GCS_MAVLink/GCS_Common.cpp#L1462).
