### ISSUE TITLE
Issue running this code

### ISSUE THREAD

**Issue by doc2142** [ArduPilot/pymavlink#28]
Whenever I try to run this code I am receiving this error.
`Need exactly one type when dumping csv from bin file.`

Not sure what it means by type? I am using bin file from a pixhawk sd card and typing this in the cmd
python mavlogdump.py data.bin --format "csv"

**Comment by peterbarker** [comment]
On Sat, 22 Oct 2016, doc2142 wrote:

> Whenever I try to run this code I am receiving this error.
> Need exactly one type when dumping csv from bin file.
> 
> Not sure what it means by type? I am using bin file from a pixhawk sd card
> and typing this in the cmd
> python mavlogdump.py data.bin --format "csv"

Supply a single type to dump using "--types":

pbarker@bluebottle:~/rc/pymavlink(master)$ mavlogdump.py --types MSG 
--format csv  ~/rc/flight-data/bixler/logs/2016-10-23/flight1/3.BIN
timestamp,TimeUS,Message
1477190523.00179505,175759293,ArduPlane V3.6.0beta1 (2b0616fa)
1477190523.00181007,175759308,PX4: af11b140 NuttX: 579e82d4
1477190523.00185990,175759358,PX4v1 00360038 35324707 39383232
1477190523.00187492,175759373,New mission
1477190526.82058501,179578083,Executing nav command ID #22
1477190526.84025288,179597751,Armed AUTO, xaccel = -0.4 m/s/s, waiting 0.2 
sec
1477190527.04000092,179797499,Triggered AUTO. GPS speed = 0.1
