### ISSUE TITLE
Failing to dump logs

### ISSUE THREAD

**Issue by HighwayStar** [ArduPilot/pymavlink#302]
When trying to dump logs with latest pymavlink code getting
```
python3 tools/mavlogdump.py --types ATT --format csv ~/log_18_2018-6-28-14-40-08.bin > test.csv
Traceback (most recent call last):
  File "tools/mavlogdump.py", line 239, in <module>
    csv_out[0] = "{:.8f}".format(last_timestamp)
NameError: name 'csv_out' is not defined

```

I have bisected code and found that first bad commit is 

commit 86ca2a4dfc6bc3ea136d8b2d2c4caeeba3b3b034
    mavlogdump: faster dumping of specific types for DF logs

**Comment by peterbarker** [comment]
On Thu, 18 Apr 2019, HighwayStar wrote:

> I have bisected code and found that first bad commit is

Thanks for doing that work.

https://github.com/ArduPilot/pymavlink/pull/303 ought to fix the problem.
