### ISSUE TITLE
tcpin-created TCP socket can't be reused

### ISSUE THREAD

**Issue by alexkrob** [ArduPilot/pymavlink#306]
If I create a `mavlink_connection` with `tcpin:{localhost}:{port}`, send some data over it, call the `close()` method (which should close the socket), and attempt to create a new `mavlink_connection` with the same argument for `device` (i.e., try and use the same port), I get the following exception: `[Errno 48] Address already in use`.

**Comment by alexkrob** [comment]
I created [this pull request](https://github.com/ArduPilot/pymavlink/pull/307) in order to address the issue. It's just a one-liner.

**Comment by peterbarker** [comment]
Thanks!
