### ISSUE TITLE
Unclear rpm unit description

### ISSUE THREAD

**Issue by Maarrk** [ArduPilot/pymavlink#374]
https://github.com/ArduPilot/pymavlink/blob/f9ab4d7a0958753de9aea9c0beb5ac4347da8559/generator/mavschema.xsd#L106

The unit is named rpm which normally means Revolutions Per Minute, but the comment describes it as:

> rotations per second

This unit is used in MAVLink [message RPM (#226) of ardupilotmega dialect](https://mavlink.io/en/messages/ardupilotmega.html#RPM), however I currently have no easy way to check if this is implemented actually as revolutions per minute or per second.

It seems to me that defining a unit for revolution per second is not needed, as one could use Hz instead. Also the name `rpm` is misleading in case revolution per second was intended.

Issue affects non-ardupilot users as well, since these unit definitions [are linked in MAVLink documentation](https://mavlink.io/en/guide/xml_schema.html#messages)

**Comment by peterbarker** [comment]
Thanks for the report.
