### ISSUE TITLE
MavLink v2 C# support

### ISSUE THREAD

**Issue by HrlecMatej** [ArduPilot/pymavlink#388]
I was looking to use MavLink v2 with C#, but it officially isn't supported.
I have though noticed, that ArduPilot's MissionPlanner has it implemented: https://github.com/ArduPilot/MissionPlanner/tree/master/ExtLibs/Mavlink

My question is, is MissionPlanner's C# message generator working? And if yes, why are there two different generators that both belong to ArduPilot?

**Comment by auturgy** [comment]
Relevant: https://github.com/ArduPilot/pymavlink/pull/322
Yes, Missionplanner’s C# generator is working. Michael made a PR to this repo but it is yet to be merged.
