### ISSUE TITLE
OBSTACLE_DISTANCE message

### ISSUE THREAD

**Issue by jimmyfraiture** [ArduPilot/pymavlink#397]
Hello,
I'm trying to send OBSTACLE_DISTANCE message from a RPi to a PX4 using pymavlink but it doesn't seem to be implemented. Is it an alternative for that?
Is it a way to send 'brut' message or do I have to build the packet myself? 

Thanks

**Comment by jmachuca77** [comment]
How did you install pymavlink? you might need to generate from source

**Comment by jimmyfraiture** [comment]
Simply using pip3 like in the doc.
How should I do then?

**Comment by jmachuca77** [comment]
Follow the instructions in this repo and install for developers 
https://github.com/ArduPilot/pymavlink#for-developers
use the latest mavlink definitions.

**Comment by jimmyfraiture** [comment]
I did that but nothing changed

**Comment by amilcarlucas** [comment]
That message is Work-in-progress. And as long as it remains so it will not be supported by the pymavlink release.
You can however use a locally compiled mavlink with the latest upstream mavlin/mavlink repository. That will work.
