### ISSUE TITLE
Qgroundcontrol connection to pixhawk via rpi and 4G (public ip)

### ISSUE THREAD

**Issue by RotemShavit** [ArduPilot/pymavlink#416]
Hi,
I am trying to connect my QGC/mission planner to my pixhawk (which is connected to a raspberry pi 3 and a cellular network with a static public ip) and the port seems to be closed. 

I am trying to do so by:
mavutil.mavlink_connection("udpout:localhost:14540") and then trying to access it from the QGC to the rpi with the public ip of the rpi (port forawrding was set) 

We cant establish the connection and when we checked the open ports list, we have seen that the 14540 port does not appear.    

Any ideas to open the port correctly or a general solution to connect rpi to QGC via cellular would really help!

**Comment by amilcarlucas** [comment]
This is not a support forum. Please use the ardupilot forums to get help
