### ISSUE TITLE
high_latency2 appears to be not provided by pymavlink 

### ISSUE THREAD

**Issue by patrickelectric** [ArduPilot/pymavlink#422]
It was not possible for me to find such message in the generated files, is there any bug or trick to use it ?

**Comment by auturgy** [comment]
It might not have been merged downstream into ardupilot/mavlink

@amilcarlucas

**Comment by amilcarlucas** [comment]
That particular message is "work-in-progress" and therefore not merged into ardupilot/mavlink

**Comment by patrickelectric** [comment]
@amilcarlucas HIGH_LATENCY2 is not WIP anymore in mavlink master branch.
https://github.com/mavlink/mavlink/pull/1406

**Comment by amilcarlucas** [comment]
It is now included in https://github.com/ArduPilot/mavlink/pull/151

This can be closed once that one gets merged

**Comment by amilcarlucas** [comment]
Done
