### ISSUE TITLE
Struct error in sample code Mavtest.py

### ISSUE THREAD

**Issue by klauspeng1** [ArduPilot/pymavlink#423]
The following error message was generated when I tried to run the Mavtest.py code using python 3
![image](https://user-images.githubusercontent.com/66589166/84482803-e8f59000-acca-11ea-8c2d-cde10d143e17.png)

It appears to be some problem with python struct not recognizing 's' as a bytes type for string.

For instance, the following code will result the same struct error
`import struct`
`a = struct.pack('s', "a")`
`print(a)`
![image](https://user-images.githubusercontent.com/66589166/84482975-3a9e1a80-accb-11ea-9c41-6d96e0016c98.png)

**Comment by TheLegendaryJedi** [comment]
Hi @klauspeng1,

You need to convert the 'a' to byte string like `a = struct.pack('s', b'a')`

**Comment by peterbarker** [comment]
mavtest.py works in master now under both Python2 and Python3  - thanks for the report.
