### ISSUE TITLE
AttributeError: module 'pymavlink.dialects.v20.common' has no attribute 'MAV_CMD_SET_CAMERA_ZOOM'

### ISSUE THREAD

**Issue by appetito** [ArduPilot/pymavlink#443]
pymavlink 2.4.9 from pip

**Comment by ryums12** [comment]
i have same problem, is there anyone can solve this problem?

**Comment by auturgy** [comment]
pymavlink releases as a rule don’t include WIP messages. When the WIP tags are removed from the command upstream it will usually be pulled down.

**Comment by peterbarker** [comment]
@ryums12 I think @auturgy has answered your question here.  Please reopen if it isn't.
