### ISSUE TITLE
Current version available on PyPI is confused

### ISSUE THREAD

**Issue by courtarro** [ArduPilot/pymavlink#56]
When I query for the current version of `pymavlink` on PyPI (using the site or `pip`), I get `2.0.6`. However, when I install the package, I end up with `2.1.0`.

Apparently `2.1.0` was uploaded on 2017-02-02, then `2.0.6` was uploaded on 2017-02-06. As a result, either PyPI is confused or `pip` is. This page shows that `2.0.6` is the latest version:

https://pypi.python.org/pypi/pymavlink

However, check this page to see the confusion:

https://pypi.python.org/pypi/pymavlink/2.1.0

That's the page for version `2.1.0`, but it shows a "Latest version" of `2.0.6`. Was `2.0.6` reuploaded on purpose, perhaps to deal with a regression? If so, `2.1.0` is what's actually being downloaded by my `pip` instance. I'm not sure why, other than it looking at the version numbers and trying to get the "highest" one. This is what I got:

    root@docker:/# pip search pymavlink
    pymavlink (2.0.6)  - Python MAVLink code

    root@docker:/# pip install pymavlink
    Collecting pymavlink
      Downloading pymavlink-2.1.0.tar.gz (2.8MB)
        100% |################################| 2.8MB 552kB/s

**Comment by paan2097** [comment]
Could it be that pymavlink 2.1.0 has problems?? Because I'm trying to run dronekit scrips with pymavlink 2.1.0 and I'm getting link timeouts.....could this be the problem?

**Comment by cclauss** [comment]
https://pypi.python.org/pypi/pymavlink 2.2.2 is current.  Can you please try that version and then describe the problems that remain?

Thanks, CCC
