### ISSUE TITLE
Cannot generate pymavlink library with custom mavlink message definitions

### ISSUE THREAD

**Issue by Saaadat** [ArduPilot/pymavlink#564]
Hello,

I followed the steps below to update the pymavlink library.

https://github.com/ArduPilot/pymavlink#for-developers

After running the command, i tested to import the library and got the following error.

Traceback (most recent call last):
  File "main.py", line 22, in <module>
    import pymavlink.mavutil as mavutil
  File "/home/lone/.local/lib/python3.8/site-packages/pymavlink/mavutil.py", line 1995, in <module>
    mavlink.MAV_TYPE_DECAROTOR:   mode_mapping_acm,
AttributeError: module 'pymavlink.dialects.v10.ardupilotmega' has no attribute 'MAV_TYPE_DECAROTOR'

Any way to get this working?

**Comment by peterbarker** [comment]
On Mon, 21 Jun 2021, Sa aadat Lone wrote:

> After running the command, i tested to import the library and got the following error.
> AttributeError: module 'pymavlink.dialects.v10.ardupilotmega' has no attribute 'MAV_TYPE_DECAROTOR'

Rebase your message definitions changes on top of ArduPilot's master 
mavlink message definitions.
