### ISSUE TITLE
pyinstaller xml Error.....

### ISSUE THREAD

**Issue by KimJinHyeok1** [ArduPilot/pymavlink#566]
hello now I'm develop the GCS program using dronekit and PyQT5, pyinstaller

in the pycharm everything work well!

so i make .exe file using Pyinstaller

but when i click Connect button (vehicle=connect(udpin:localhost:port))

In the console print "warning: unable to load xml validator libraries. xml validation will not be performed"

I'm doing almost solution in the internet ( ex: hidden import lxml, lxml.etree...., reinstall pyinstaller,pymavlink,mavutil...)
but error is same..

I'm really don't know why that error occur only in the .exe file..

Pleeeeeeeeeease. Let me know any solution..... 

Thankyou

**Comment by peterbarker** [comment]
On Wed, 23 Jun 2021, KimJinHyeok1 wrote:

> In the console print "warning: unable to load xml validator libraries. xml validation will not be performed"

Missing lxml Python package.
