### ISSUE TITLE
how to cite in paper

### ISSUE THREAD

**Issue by zboucek** [ArduPilot/pymavlink#572]
I would like to cite this package in my paper. Is there a suitable paper decribing pymavlink?

**Comment by peterbarker** [comment]
On Wed, 14 Jul 2021, Zdeněk Bouček wrote:

> I would like to cite this package in my paper. Is there a suitable paper decribing pymavlink?

I'm certainly not aware of one.

Best bet is simply to reference the repo on github - perhaps 
https://github.com/ardupilot/pymavlink#readme
