### ISSUE TITLE
tostring() deprecated in python3.9

### ISSUE THREAD

**Issue by rbeall-kha** [ArduPilot/pymavlink#587]
Testing Mavlink2.0 packet signing setup function and failed.
https://github.com/ArduPilot/pymavlink/blob/master/generator/mavgen_python.py#L712

tostring() has been deprecated in python3.9:
https://docs.python.org/3/whatsnew/3.9.html

**Comment by peterbarker** [comment]
@rbeall-kha are you in a position to test https://github.com/ArduPilot/pymavlink/pull/588 ?
