### ISSUE TITLE
Message definitions directory for Mavlink2.0 is ./v1.0

### ISSUE THREAD

**Issue by basil-huber** [ArduPilot/pymavlink#598]
Hi folks,

Message definitions for Mavlink2.0 are expected to be in a directory called `v20` or `v1.0` instead of `v2.0`. Is there any particular reason or is this just a copy paste bug?
Code: https://github.com/ArduPilot/pymavlink/blob/069ae75a9c7116656f0f8f006141dbbe95859028/generator/mavgen.py#L319

Cheers,
Basil

**Comment by peterbarker** [comment]
@basil-huber not a copy/paste bug.  It was just decided that the message definitions used for 2.0 would be exactly the same as 1.0 to aid in backwards-compatability.

I don't think that's going to change.

**Comment by basil-huber** [comment]
Ok, fair enough. Will close the PR in that case
