### ISSUE TITLE
mavlink_helpers.h:581: error: switch missing default case [-Werror=switch-default]   switch (status->parse_state)

### ISSUE THREAD

**Issue by AleksandrBon** [ArduPilot/pymavlink#604]
compiler: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
flags:
-std=c++11
-Wall
-Wextra
-Werror
 -Wswitch-default

Again like in previous case #603 one can switch off Wswitch-default flag, but... then such types of errors will be hard to find in the rest user code.

**Comment by peterbarker** [comment]
@AleksandrBon you should be able to compile the code with `-Wswitch`, which is a tighter check.

We don't want `default:` as older compilers don't have `-Wswitch-enum`- meaning you can't catch the cases where you add an enum entry and don't address all places which need to consider the new entry.

Please reopen if you'd like to argue further :-)
