### ISSUE TITLE
qgroundcontrol[.]org domain not available, but still exists in the code

### ISSUE THREAD

**Issue by Tiryoh** [ArduPilot/pymavlink#609]
According to this issue https://github.com/ArduPilot/pymavlink/issues/35 and https://github.com/ArduPilot/pymavlink/pull/199, qgroundcontrol[.]org domain is outdated, but there are still used in the comment.

https://github.com/ArduPilot/pymavlink/search?q=qgroundcontrol+org&type=code

I guess the link should be updated to https://mavlink.io/en/.

**Comment by peterbarker** [comment]
I've created #614 to fix this - any review would be nice.

**Comment by Tiryoh** [comment]
@peterbarker Thanks! It's already merged, but I checked. It looks great!

**Comment by peterbarker** [comment]
Thanks @Tiryoh :-)
