### ISSUE TITLE
Using tlog to get the version of the Mavlink protocol used

### ISSUE THREAD

**Issue by emmaemmstein** [ArduPilot/pymavlink#659]
Is there a way to know the version of Mavlink protocol used from the tlog file? If yes, how? I have gone through this link [https://mavlink.io/en/guide/mavlink_version.html] but don't know how to implement this either. I am new in this space and would appreciate help on this problem, thanks.

**Comment by peterbarker** [comment]
On Thu, 7 Apr 2022, emmaemmstein wrote:

> Is there a way to know the version of Mavlink protocol used from the tlog file? If yes, how? I have gone through this link [https://mavlink.io/en/guide/mavlink_version.html] but don't know how to implement this either. I am new in this space and would appreciate help on this problem, thanks.

No reason you can't have messages of both types in the log.

Each message will have its version in its header.
