### ISSUE TITLE
extracting a bunch of parameters from tlog file

### ISSUE THREAD

**Issue by emmaemmstein** [ArduPilot/pymavlink#660]
I saw this code [here](https://github.com/ArduPilot/pymavlink/blob/master/tools/mavparms.py) which extracted param_id and their values. I wanted to know how I could modify it to print out more data (like Longitude, altitude, latitude etc) and their resulting values. I know data like this exist because I can access them from their csv format but they are not printed out using the mavparms.py code. Pardon my ignorance as I am new to using pymavlink.

Thanks

**Comment by emmaemmstein** [comment]
I Found my way around it

**Comment by brunoolivieri** [comment]
@emmaemmstein My I ask how? :-)

**Comment by emmaemmstein** [comment]
I used the '.recv_match()'  method. No argument was passed in it so it
printed all the message

**Comment by brunoolivieri** [comment]
thanks
