### ISSUE TITLE
GPS_RAW_INT fix_type is not updating correctly

### ISSUE THREAD

**Issue by CodingGhost** [ArduPilot/pymavlink#669]
I noticed that when trying to read the GPS fix type, it will first report the correct type, but the value will not change if the type changes.
when restarting the scripts, the type is again read correctly but does not update.
tested using
msg = master.messages['GPS_RAW_INT']
print(msg)

**Comment by peterbarker** [comment]
@CodingGhost which autopilot are you reading data from?  Is the timestamp changing on the message you're receiving?

I've just tested locally in simulation and it seems to be working just fine.

**Comment by CodingGhost** [comment]
Im reading from a cube orange. If you can give me your test python, I can test it tomorrow using your script to make sure its not my error

**Comment by CodingGhost** [comment]
update: I got it working with master.recv_match instead of .messages... is that expected?

**Comment by peterbarker** [comment]
On Mon, 2 May 2022, Jonas Woerner wrote:

> update: I got it working with master.recv_match instead of .messages... is that expected?

Yes; messages is a cache of the most recent of each message parsed - 
recv_match will update that on each message received.
