### ISSUE TITLE
Wireshark showing 0 for negative int32

### ISSUE THREAD

**Issue by hamishwillee** [ArduPilot/pymavlink#701]
With mission items with negative y (negative int32 value), the wireshark plugin incorrectly shows 0, even though the data is clearly not 0 (as seen in the hex dump)

![](https://user-images.githubusercontent.com/8969570/177126837-024d07ab-7748-4c09-a8fa-fa29b71dfcfd.png)

This is cross posted from https://github.com/mavlink/mavlink/issues/1862

**Comment by peterbarker** [comment]
@PurkkaKoodari any ideas on this one?  I figure your recent work on this generator makes you the most likely to nail this in short order :-)

**Comment by PurkkaKoodari** [comment]
I haven't been working on the previous ArduPilot-based project in over a year, so I my experience isn't exactly fresh, but I'll take a look.

@hamishwillee Can you share a `.pcapng` with this packet? The code I have installed locally - not sure if it matches upstream - seems to be parsing negative int32_t's just fine. (You can use File->Export Specified Packets if you want to limit the amount of data shared.)

![image](https://user-images.githubusercontent.com/8439661/177738343-df587b19-b416-48a9-8e36-43726b4148ea.png)

**Comment by hamishwillee** [comment]
@PurkkaKoodari Thanks! I'm actually just cross posting this on behalf of @ThomasDebrunner - Thomas, could you please provide a .pcappng with the packet to allow easier testing?

**Comment by ThomasDebrunner** [comment]
Just tried to reproduce again and get a pcapng, but it seems to be working now on my Ubuntu. I spottet the problem on my mac, so maybe it is platform related? Will try again on the mac later.
