### ISSUE TITLE
Repo needs a LICENSE file

### ISSUE THREAD

**Issue by cclauss** [ArduPilot/pymavlink#71]
This repo needs a license file.  https://help.github.com/articles/licensing-a-repository

**Comment by ferret-guy** [comment]
I wanted to follow up on this, I think it would be useful. In addition, this would enable automatic PyPI releases with tagged commits.

@tridge

**Comment by ferret-guy** [comment]
On the Licence front, I agree we need one; it should probably be LGPL. There is plenty of conflicting information, in [setup.py](https://github.com/ArduPilot/pymavlink/blob/master/setup.py) it has `license='LGPLv3'` but there are plenty of files like [pymavlink/mavexpression.py](https://github.com/ArduPilot/pymavlink/blob/master/mavexpression.py) which has the text `Released under GNU GPL version 3 or later` that is incompatible, but it looks like they were all committed by @tridge so conceivably he could move it to GPL.

**Comment by cclauss** [comment]
Original (Would it be possible to start using https://github.com/ArduPilot/pymavlink/releases ?  Or at least a changelog?) was a duplicate of #6

**Comment by amilcarlucas** [comment]
@tridge this one should be easy to fix and it is important

**Comment by khancyr** [comment]
there is already a license file : COPYING 
but we should address the licensing on file issue
