### ISSUE TITLE
TypeError on .bin file to json when running mavlogdump.py

### ISSUE THREAD

**Issue by nedraebb** [ArduPilot/pymavlink#730]
The command I am using is **python mavlogdump.py --format json filename.bin > filename.bin.json**

Raises TypeError(f'Object of type {o.__class__.name__}')
TypeError: Object of type bytes is not JSON serializable

I have tried this on multiple .bin files and it prints about 1400 hundred lines into the output file before it fails. Is anyone able to recreate this?

**Comment by peterbarker** [comment]
@nedraebb could you test the linked PR, please?  Note the caveat that file content won't be recoverable afterwards.

**Comment by nedraebb** [comment]
@peterbarker Tested this out on a few different .bin files and it is working. Thanks!

**Comment by peterbarker** [comment]
> @peterbarker Tested this #731 on a few different .bin files and it is working. Thanks! I am confused as to what you mean by the file content won't be recoverable after.

I'm not attempting to preserve the file content.  To represent it in JSON would require base64-encoding it or similar, in case you wanted to extract the file content from the JSON.  Can't do binary in JSON files, must be valid utf-8 AFAIK.

**Comment by peterbarker** [comment]
... and to be clear, ArduPilot embeds some file content within the dataflash logs.  It's in the `FILE` dataflash log message.
