### ISSUE TITLE
Pointless API methods

### ISSUE THREAD

**Issue by edwinhayes** [ArduPilot/pymavlink#79]
Why does the generator populate the `MAVLink` class with (nominally) hundreds of methods to 'encode' and 'send' all the various message types?  Those methods are just wrappers for instantiating message classes, and calling `send()`.  Is there really some value in providing wrappers for these, at the cost of making the generated python file and generated documentation way longer than it needs to be?

Obviously, one million things probably use this API, but I just want to understand what the design intent was.

**Comment by tridge** [comment]
they are used by some applications, eg. when you want to encode a packet but queue it for send by another thread
