### ISSUE TITLE
Inconsistent arm/disarm state

### ISSUE THREAD

**Issue by SourabhPrasad** [ArduPilot/pymavlink#792]
Hi, 
I am trying to read the arm/disarm state of my drone, running ardupilot, using using pymavlink connected to the drone via UDP.
A [herelink](https://docs.cubepilot.org/user-guides/herelink/herelink-overview) controller is also connected to the drone. With there herelink connected, the pymavlink reports inconsistent arm/disarm state. It constantly fluctuates between arm and disarm. 
![Screenshot from 2023-04-05 13-11-40](https://user-images.githubusercontent.com/20325484/230052127-f3d7b87f-70d5-4d50-ac81-ca4eccddc1f7.png)

QGC and Mission Planner does not have this inconsistency. Disconnecting the herelink eliminated the fluctuation.

On testing with MAVProxy with herelink shows addition vehicles.
![Screenshot from 2023-04-05 13-11-21](https://user-images.githubusercontent.com/20325484/230052956-5f9105ca-ca76-4798-af45-72430550494e.png)

Is there a way to ignore the addition vehicle detected?

**Comment by peterbarker** [comment]
On Wed, 5 Apr 2023, Cryoschrome wrote:

> Is there a way to ignore the addition vehicle detected?

https://github.com/ArduPilot/pymavlink/pull/794 may fix the problem.

**Comment by SourabhPrasad** [comment]
Hey, that fixed the issue. Thanks!
