### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by anunarayan13** [ArduPilot/pymavlink#849]
from pymavlink.dialects.v10 import ardupilotmega as MAV_APM
  File "/usr/local/lib/python2.7/dist-packages/pymavlink-2.4.39-py2.7.egg/pymavlink/dialects/v10/ardupilotmega.py", line 56
    def __init__(self, buf: Optional[Sequence[int]] = None) -> None:
                                    ^
SyntaxError: invalid syntax

Please resolve

**Comment by shancock884** [comment]
From your path it looks like you are using python2.7 - the website suggests that pymavlink is only supported from Python 3.5 onwards, so maybe this is the reason. (to be confirmed by someone more authoritative than me...)

**Comment by Menny11** [comment]
pymavlink is used by dronekit and there is only 2.7 python supported(( I don't now why the support for py2 in the pymavlink is removed(

**Comment by khancyr** [comment]
py2 is deprecatead since some years already and it become too hard to maintain compatiblity with it as most project are dropping py2, so ArduPilot move to python3 only and update most of its tools for this.

**Comment by furkanisikay** [comment]
please run this command on your terminal to using pymavlink 2.4.37. it going to fix your problem.

pip install --force-reinstall -v "pymavlink==2.4.37"

**Comment by peterbarker** [comment]
Closing this as no response from @anunarayan13

**Comment by peterbarker** [comment]
(thanks all!)
