### ISSUE TITLE
my script corrupt logs files

### ISSUE THREAD

**Issue by ozitoune** [ArduPilot/pymavlink#874]
Hello , i have a script to list logs files , choise one and download it. It work but logs.px4.io tell me the file is corrupted .
Here is my code : 
(i'm sory i can put it in code mode it separate my code?!)

import os
from pymavlink import mavutil

def connect_pixhawk(port='/dev/ttyACM0', baud=57600):
    print(f"Connexion au Pixhawk sur {port} avec un baud rate de {baud}")
    master = mavutil.mavlink_connection(port, baud=baud)
    master.wait_heartbeat()
    print("Pixhawk connecté!")
    return master

def list_logs(master):
    master.mav.log_request_list_send(master.target_system, master.target_component, 0, 0xFFFF)
    logs = {}
    last_log_num = None

    while True:
        msg = master.recv_match(type='LOG_ENTRY', blocking=True)
        if msg is None:
            continue
        print(f"Log ID: {msg.id}, Taille: {msg.size}")
        logs[msg.id] = msg.size
        last_log_num = msg.last_log_num

        if msg.id == last_log_num:
            break
    return logs

def download_log(master, log_id, log_size, directory):
    print(f"Téléchargement du log {log_id}...")
    master.mav.log_request_data_send(master.target_system, master.target_component, log_id, 0, 0xFFFFFFFF)

    file_path = os.path.join(directory, f"log_{log_id}.bin")
    with open(file_path, 'wb') as log_file:
        received_bytes = 0
        while received_bytes < log_size:
            msg = master.recv_match(type='LOG_DATA', blocking=True)
            if msg is None or msg.id != log_id:
                continue
            log_file.seek(msg.ofs)
            log_file.write(bytes(msg.data))
            received_bytes = msg.ofs + len(msg.data)

    print(f"Log {log_id} téléchargé dans {directory}")

master = connect_pixhawk()
logs = list_logs(master)

log_id = int(input("Entrez l'ID du log à télécharger: "))
if log_id in logs:
    download_log(master, log_id, logs[log_id], "/home/zit/logs")
else:
    print("ID de log invalide.")

master.close()
print("Connexion fermée.")

How can i do to have logs file not corrupted ?

Thanks for any help

**Comment by peterbarker** [comment]
You should be ensuring all data has been received; sometimes packets are lost within stacks or even corruption across a USB link.

Given MAVProxy downloads logs without issue from ArduPilot, I can't see this as a problem with pymavlink and this I'm closing this issue,
