### ISSUE TITLE
future module error

### ISSUE THREAD

**Issue by medhijk** [ArduPilot/pymavlink#90]
While running the sim_vehicle.py I'm getting this error message.

[4/4] Processing modules/mavlink/message_definitions/v1.0/ardupilotmega.xml
Traceback (most recent call last):
  File "/home/medhijk/ardupilot/modules/mavlink/pymavlink/tools/mavgen.py", line 16, in <module>
    from pymavlink.generator import mavgen
  File "/home/medhijk/ardupilot/modules/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
**ImportError: No module named future**

mavgen returned 1 error code
Waf: Leaving directory `/home/medhijk/ardupilot/build/sitl'
Build failed
 -> task in 'mavlink' failed (exit status 1): 
	{task 139927157712448: mavgen ardupilotmega.xml -> }
''
SIM_VEHICLE: Build failed
SIM_VEHICLE: Killing tasks

I thought it's missing the future module and so tried installing future by this command: 
**pip install future**
But I get a message from the terminal as:
**Requirement already satisfied: future in /usr/local/lib/python3.5/dist-packages**

Can anyone suggest a way out of this?

**Comment by khancyr** [comment]
Hello, 
Use pip2 install future

**Comment by medhijk** [comment]
Thanks, that works!

**Comment by WaldenLeefx** [comment]
@khancyr Thank you very much, it works!!!
