### ISSUE TITLE
An error occurred when installing pymavlink through pip

### ISSUE THREAD

**Issue by FSYR-H** [ArduPilot/pymavlink#980]
This is my installation method
`pip install pymavlink`
Prompt after installation:
` Using cached pymavlink-2.4.41-py3-none-any.whl (11.6 MB)
Installing collected packages: pymavlink
Successfully installed pymavlink-2.4.41`

after this I use this to check:
`pip list`
it's show:
`PS D:\Python_project> pip list
Package    Version
---------- -------
future     1.0.0
iso8601    2.1.0
lxml       5.3.0
MAVProxy   1.8.71
numpy      2.1.1
pip        24.2
pymavlink  2.4.41
pynmeagps  1.0.42
pyserial   3.5
PyYAML     6.0.2
serial     0.0.97
setuptools 75.1.0`

after that i try:
`import serial
import serial.tools.list_ports
import pymavlink
from pymavlink import mavutil
`

it's show
`Traceback (most recent call last):
  File "d:\Python_project\1serial.py", line 3, in <module>
    import pymavlink
ModuleNotFoundError: No module named 'pymavlink'`

how shold i do now?

**Comment by peterbarker** [comment]
This can happen when your `pip` isn't the one that corresponds to your `python`.  This is why its recommended to `python3 -m pip install pymavlink` - and similarly  for other packages.
