### ISSUE TITLE
Need help in XML to KML.

### ISSUE THREAD

**Issue by prabaljainn** [ArduPilot/pymavlink#982]
I have a mission builder made by me as a service, I have these XMLs that are generated that i use to automate fly my drone.
I use Ardupilot.

I would also like to run this XML file in my DJI drone.
how to convert these XML files to DJI KML/KMZ files???

**Comment by prabaljainn** [comment]
@khancyr Please Help

**Comment by khancyr** [comment]
Hello, you need to look at DJI documentation, that isn't related to pymavlink.
